### ISSUE TITLE
Fix issues highlighted by KDL

### ISSUE THREAD

**Issue by harryjmoss** [LibCrowds/docs#3]
- Most internal links are broken and lead to 404 errors
- Documentation refers to vagrant for libcrowds installation when it is not used
- Libcrowds needs a config file to be copied, this step needs including
- Missing closing quote in Setup > Configuring PYBOSSA in `CATEGORY_INFO_PUBLIC_FIELDS`

**Comment by harryjmoss** [comment]
@mialondon I've fixed these in a local branch, could I have access rights to push these and make a pull request?

**Comment by mialondon** [comment]
@harryjmoss I've made you an owner so you should be good to go
